export interface Module {
  id: string;
  day: number;
  title: string;
  description: string;
  objectives: string[];
  outcomes: string[];
  topics: string[];
  duration: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  content: string;
}

export interface Course {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  modules: Module[];
  totalDays: number;
  difficulty: string;
}

export const gitCourse: Course = {
  id: 'git-expert',
  title: 'Git Expert Mastery',
  description: 'Master Git version control and become an expert in repository management, branching strategies, and collaboration workflows.',
  icon: '📚',
  color: 'from-orange-500 to-red-500',
  totalDays: 15,
  difficulty: 'Beginner to Advanced',
  modules: [
    {
      id: 'git-day-1',
      day: 1,
      title: 'What is Git and Why It Matters',
      description: 'Introduction to version control and Git fundamentals',
      objectives: [
        'Understand what Git is and why it\'s essential',
        'Learn the history and philosophy of Git',
        'Understand the difference between Git and GitHub',
      ],
      outcomes: [
        'Explain Git\'s purpose in software development',
        'Identify key Git concepts and terminology',
        'Understand when and why to use version control',
      ],
      topics: [
        'What is version control?',
        'Git vs other version control systems',
        'Git workflow overview',
        'Key Git concepts: repositories, commits, branches',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Git is a distributed version control system that tracks changes in your code. It allows multiple developers to work on the same project without conflicts, maintains a complete history of all changes, and enables easy collaboration. Git is essential for professional software development and is used by virtually every tech company in the world.',
    },
    {
      id: 'git-day-2',
      day: 2,
      title: 'Setting Up Your First Git Environment',
      description: 'Install and configure Git for your system',
      objectives: [
        'Install Git on your operating system',
        'Configure Git with your identity',
        'Create your first repository',
      ],
      outcomes: [
        'Successfully install and configure Git',
        'Create and initialize a Git repository',
        'Understand basic Git configuration',
      ],
      topics: [
        'Installing Git on Windows, Mac, and Linux',
        'Configuring user name and email',
        'Creating your first repository',
        'Understanding .git directory',
      ],
      duration: '1-2 hours',
      difficulty: 'Beginner',
      content: 'Setting up Git involves installing it on your system and configuring it with your user information. This configuration is important because every commit you make will be attributed to this identity. Once configured, you can initialize a new repository or clone an existing one to start working with Git.',
    },
    {
      id: 'git-day-3',
      day: 3,
      title: 'Basic Git Commands - Add, Commit, Status',
      description: 'Learn the essential Git commands for daily work',
      objectives: [
        'Master git add, commit, and status commands',
        'Understand the staging area concept',
        'Learn to write effective commit messages',
      ],
      outcomes: [
        'Stage and commit changes confidently',
        'Check repository status at any time',
        'Write clear, professional commit messages',
      ],
      topics: [
        'git status - checking your repository state',
        'git add - staging changes',
        'git commit - saving snapshots',
        'Writing good commit messages',
        'The three states of Git files',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'The three basic Git commands you\'ll use every day are status (to see what changed), add (to stage changes), and commit (to save a snapshot). Understanding the staging area is crucial - it lets you choose exactly which changes to include in each commit, giving you precise control over your project history.',
    },
    {
      id: 'git-day-4',
      day: 4,
      title: 'Viewing History and Differences',
      description: 'Learn to view and understand your project history',
      objectives: [
        'View commit history with git log',
        'Compare changes with git diff',
        'Understand commit hashes and references',
      ],
      outcomes: [
        'Navigate through project history',
        'See differences between versions',
        'Identify specific commits and changes',
      ],
      topics: [
        'git log - viewing commit history',
        'git diff - seeing what changed',
        'Commit hashes and references',
        'Viewing file history',
        'Filtering and searching logs',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Git log shows your project\'s history as a series of commits. Git diff shows exactly what changed between versions. These commands are essential for understanding what happened in your project, debugging issues, and tracking down when bugs were introduced.',
    },
    {
      id: 'git-day-5',
      day: 5,
      title: 'Undoing Changes - Reset, Revert, Checkout',
      description: 'Learn to undo mistakes and restore previous versions',
      objectives: [
        'Understand different ways to undo changes',
        'Use git reset, revert, and checkout safely',
        'Know when to use each undo command',
      ],
      outcomes: [
        'Undo changes confidently without losing work',
        'Restore files from previous commits',
        'Choose the right undo command for each situation',
      ],
      topics: [
        'Undoing unstaged changes',
        'Undoing staged changes',
        'Undoing commits with reset',
        'Undoing commits with revert',
        'Restoring individual files',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Mistakes happen, and Git provides multiple ways to undo them. Reset moves your branch pointer backward, revert creates a new commit that undoes changes, and checkout lets you restore individual files. Each serves a different purpose and it\'s important to know when to use which.',
    },
    {
      id: 'git-day-6',
      day: 6,
      title: 'Understanding Branches',
      description: 'Master Git branching for parallel development',
      objectives: [
        'Understand what branches are and why they matter',
        'Create and switch between branches',
        'Learn branching best practices',
      ],
      outcomes: [
        'Create branches for new features',
        'Switch between branches confidently',
        'Understand branch-based workflows',
      ],
      topics: [
        'What are branches?',
        'Creating branches',
        'Switching branches',
        'Branch naming conventions',
        'When to create branches',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Branches are one of Git\'s most powerful features. They let you work on different features or experiments in isolation, without affecting the main codebase. Think of branches as parallel universes for your code - you can try things out, and if they work, merge them back; if not, just delete the branch.',
    },
    {
      id: 'git-day-7',
      day: 7,
      title: 'Merging Branches',
      description: 'Combine work from different branches',
      objectives: [
        'Understand how merging works',
        'Perform fast-forward and three-way merges',
        'Handle merge conflicts',
      ],
      outcomes: [
        'Merge branches successfully',
        'Resolve merge conflicts confidently',
        'Understand different merge strategies',
      ],
      topics: [
        'Fast-forward merges',
        'Three-way merges',
        'Merge conflicts',
        'Resolving conflicts',
        'Merge strategies and options',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Merging combines changes from different branches. Sometimes Git can merge automatically (fast-forward), but when the same lines were changed in different ways, you get a conflict that needs manual resolution. Learning to handle conflicts is an essential Git skill.',
    },
    {
      id: 'git-day-8',
      day: 8,
      title: 'Working with Remote Repositories',
      description: 'Connect to GitHub and collaborate with others',
      objectives: [
        'Understand remote repositories',
        'Connect local repo to GitHub',
        'Push and pull changes',
      ],
      outcomes: [
        'Connect repositories to GitHub',
        'Push your code to remote repositories',
        'Pull changes from others',
      ],
      topics: [
        'What are remotes?',
        'Adding remote repositories',
        'Pushing changes',
        'Pulling changes',
        'Fetching vs pulling',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Remote repositories are versions of your project hosted on the internet (like GitHub). They enable collaboration and backup. Push sends your local commits to the remote, pull brings remote changes to you, and fetch updates your knowledge of remote changes without merging them.',
    },
    {
      id: 'git-day-9',
      day: 9,
      title: 'Cloning and Forking Repositories',
      description: 'Start working with existing projects',
      objectives: [
        'Clone repositories from GitHub',
        'Understand forking',
        'Contribute to open source projects',
      ],
      outcomes: [
        'Clone any repository to your computer',
        'Fork repositories on GitHub',
        'Understand when to fork vs clone',
      ],
      topics: [
        'Cloning repositories',
        'Forking on GitHub',
        'Upstream repositories',
        'Contributing to open source',
        'Clone vs fork comparison',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Cloning copies a repository to your local machine. Forking creates your own copy on GitHub that you control. Cloning is for projects you have write access to, forking is for contributing to projects you don\'t own. Both are essential for collaboration.',
    },
    {
      id: 'git-day-10',
      day: 10,
      title: 'Git Workflows and Best Practices',
      description: 'Learn professional Git workflows',
      objectives: [
        'Understand common Git workflows',
        'Learn feature branch workflow',
        'Master commit best practices',
      ],
      outcomes: [
        'Follow professional Git workflows',
        'Work effectively in teams',
        'Write high-quality commits',
      ],
      topics: [
        'Feature branch workflow',
        'Git flow',
        'GitHub flow',
        'Commit message conventions',
        'Branch naming conventions',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Professional teams follow established Git workflows to coordinate their work. The feature branch workflow is most common: create a branch for each feature, develop it in isolation, then merge it back. Following conventions makes collaboration smoother and code reviews easier.',
    },
    {
      id: 'git-day-11',
      day: 11,
      title: 'Pull Requests and Code Review',
      description: 'Collaborate effectively on GitHub',
      objectives: [
        'Create pull requests on GitHub',
        'Review code effectively',
        'Respond to review feedback',
      ],
      outcomes: [
        'Create clear pull requests',
        'Conduct thorough code reviews',
        'Iterate on feedback professionally',
      ],
      topics: [
        'Creating pull requests',
        'Writing good PR descriptions',
        'Code review best practices',
        'Responding to feedback',
        'Merging pull requests',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Pull requests are how teams review and merge code on GitHub. They let others see your changes, comment on them, suggest improvements, and approve them before merging. Good PRs have clear descriptions, focused changes, and welcome feedback.',
    },
    {
      id: 'git-day-12',
      day: 12,
      title: 'Advanced Git - Rebase and Cherry-pick',
      description: 'Master advanced Git techniques',
      objectives: [
        'Understand rebasing vs merging',
        'Use interactive rebase',
        'Cherry-pick specific commits',
      ],
      outcomes: [
        'Rebase branches safely',
        'Clean up commit history',
        'Apply specific commits selectively',
      ],
      topics: [
        'What is rebasing?',
        'Rebase vs merge',
        'Interactive rebase',
        'Cherry-picking commits',
        'When to use each technique',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Rebase rewrites commit history by moving commits to a new base. It creates a cleaner, linear history but should be used carefully. Cherry-pick lets you apply specific commits from one branch to another. Both are powerful tools for maintaining clean project history.',
    },
    {
      id: 'git-day-13',
      day: 13,
      title: 'Git Stash and Cleaning',
      description: 'Manage work-in-progress and clean your workspace',
      objectives: [
        'Use git stash for temporary changes',
        'Clean untracked files safely',
        'Manage multiple stashes',
      ],
      outcomes: [
        'Stash changes when switching context',
        'Clean workspace efficiently',
        'Recover stashed work',
      ],
      topics: [
        'Stashing changes',
        'Applying stashes',
        'Stash management',
        'Cleaning untracked files',
        'git clean options',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Stash temporarily saves uncommitted changes so you can switch contexts without committing half-done work. It\'s perfect for when you need to quickly switch branches but aren\'t ready to commit. Git clean removes untracked files to keep your workspace tidy.',
    },
    {
      id: 'git-day-14',
      day: 14,
      title: 'Git Tags and Releases',
      description: 'Mark important points in your project history',
      objectives: [
        'Create and manage tags',
        'Understand semantic versioning',
        'Create releases on GitHub',
      ],
      outcomes: [
        'Tag releases appropriately',
        'Follow semantic versioning',
        'Create GitHub releases',
      ],
      topics: [
        'Lightweight vs annotated tags',
        'Semantic versioning (SemVer)',
        'Tagging releases',
        'Creating GitHub releases',
        'Release management',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Tags mark specific points in history as important, usually releases. Semantic versioning (1.2.3) uses major.minor.patch numbering to communicate the type of changes. Tags make it easy to reference and deploy specific versions of your software.',
    },
    {
      id: 'git-day-15',
      day: 15,
      title: 'Git for Outlier Success',
      description: 'Apply Git knowledge to Outlier assessments',
      objectives: [
        'Understand Outlier\'s Git requirements',
        'Practice common assessment scenarios',
        'Master Git troubleshooting',
      ],
      outcomes: [
        'Confidently use Git in Outlier assessments',
        'Solve common Git problems quickly',
        'Follow professional Git practices',
      ],
      topics: [
        'Git commands for Outlier assessments',
        'Common assessment scenarios',
        'Troubleshooting Git issues',
        'Best practices for assessments',
        'Time-saving Git tricks',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'This final module brings everything together, focusing on using Git effectively in Outlier assessments. You\'ll practice common scenarios, learn troubleshooting techniques, and master the workflow expected by Outlier reviewers. By the end, Git will be second nature.',
    },
  ],
};

export const pythonCourse: Course = {
  id: 'python-expert',
  title: 'Python Expert Mastery',
  description: 'Master Python programming from basics to advanced techniques, including OOP, data structures, and professional development practices.',
  icon: '🐍',
  color: 'from-blue-500 to-cyan-500',
  totalDays: 15,
  difficulty: 'Beginner to Advanced',
  modules: [
    {
      id: 'python-day-1',
      day: 1,
      title: 'What is Python and Your First Program',
      description: 'Introduction to Python and writing your first program',
      objectives: [
        'Understand what Python is and its uses',
        'Install Python on your system',
        'Write and run your first Python program',
      ],
      outcomes: [
        'Explain Python\'s purpose and popularity',
        'Install Python and verify installation',
        'Write a simple "Hello, World!" program',
      ],
      topics: [
        'What is Python?',
        'Why Python is popular',
        'Installing Python',
        'Running Python code',
        'Your first program: print()',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Python is a high-level, interpreted programming language known for its simplicity and readability. It\'s used in web development, data science, artificial intelligence, automation, and many other fields. Python\'s syntax is designed to be intuitive, making it an excellent language for beginners while remaining powerful enough for professionals.',
    },
    {
      id: 'python-day-2',
      day: 2,
      title: 'Variables, Data Types, and Basic Operations',
      description: 'Learn about variables, data types, and performing calculations',
      objectives: [
        'Understand variables and naming conventions',
        'Learn Python\'s basic data types',
        'Perform mathematical operations',
      ],
      outcomes: [
        'Create and use variables correctly',
        'Identify and work with different data types',
        'Perform calculations and string operations',
      ],
      topics: [
        'Variables and assignment',
        'Data types: strings, integers, floats, booleans',
        'Type conversion',
        'Mathematical operations',
        'String manipulation',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Variables are containers for storing data values. Python supports several basic data types including strings (text), integers (whole numbers), floats (decimal numbers), and booleans (True/False). Understanding these types and how to work with them is fundamental to programming in Python.',
    },
    {
      id: 'python-day-3',
      day: 3,
      title: 'Input, Output, and String Formatting',
      description: 'Learn to get user input and format output',
      objectives: [
        'Get input from users',
        'Format output professionally',
        'Work with f-strings and formatting',
      ],
      outcomes: [
        'Create interactive programs',
        'Format strings beautifully',
        'Handle user input safely',
      ],
      topics: [
        'input() function',
        'print() with multiple arguments',
        'F-strings and formatting',
        'String methods',
        'Formatting numbers and dates',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Getting input from users and displaying output professionally are essential skills. Python\'s f-strings make formatting easy and readable. You\'ll learn to create interactive programs that communicate clearly with users.',
    },
    {
      id: 'python-day-4',
      day: 4,
      title: 'Conditional Statements - If, Elif, Else',
      description: 'Make decisions in your code',
      objectives: [
        'Understand boolean logic',
        'Write if/elif/else statements',
        'Use comparison and logical operators',
      ],
      outcomes: [
        'Make programs that respond to conditions',
        'Write complex conditional logic',
        'Use boolean operators effectively',
      ],
      topics: [
        'If statements',
        'Elif and else',
        'Comparison operators',
        'Logical operators (and, or, not)',
        'Nested conditionals',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Conditional statements let your programs make decisions. If this is true, do that; otherwise, do something else. This is fundamental to creating programs that respond intelligently to different situations.',
    },
    {
      id: 'python-day-5',
      day: 5,
      title: 'Loops - For and While',
      description: 'Repeat actions efficiently',
      objectives: [
        'Write for loops',
        'Write while loops',
        'Understand when to use each loop type',
      ],
      outcomes: [
        'Iterate over sequences with for loops',
        'Create conditional loops with while',
        'Avoid infinite loops',
      ],
      topics: [
        'For loops with range()',
        'For loops with lists',
        'While loops',
        'Break and continue',
        'Loop patterns',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Loops let you repeat actions without writing repetitive code. For loops iterate over sequences (like lists or ranges), while loops continue until a condition becomes false. Mastering loops is essential for efficient programming.',
    },
    {
      id: 'python-day-6',
      day: 6,
      title: 'Lists and List Operations',
      description: 'Work with collections of data',
      objectives: [
        'Create and modify lists',
        'Use list methods',
        'Understand list indexing and slicing',
      ],
      outcomes: [
        'Store multiple values in lists',
        'Access and modify list elements',
        'Use list comprehensions',
      ],
      topics: [
        'Creating lists',
        'Indexing and slicing',
        'List methods (append, insert, remove)',
        'List comprehensions',
        'Nested lists',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Lists are ordered collections that can hold multiple values. They\'re one of Python\'s most versatile data structures. You can add, remove, search, and sort items. List comprehensions provide a concise way to create lists.',
    },
    {
      id: 'python-day-7',
      day: 7,
      title: 'Functions - Creating Reusable Code',
      description: 'Write modular, reusable code',
      objectives: [
        'Define and call functions',
        'Use parameters and return values',
        'Understand scope',
      ],
      outcomes: [
        'Create custom functions',
        'Write DRY (Don\'t Repeat Yourself) code',
        'Use functions to organize programs',
      ],
      topics: [
        'Defining functions',
        'Parameters and arguments',
        'Return values',
        'Variable scope',
        'Default parameters',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Functions are reusable blocks of code that perform specific tasks. They help organize your code, make it more readable, and avoid repetition. Good functions do one thing well and can be reused throughout your program.',
    },
    {
      id: 'python-day-8',
      day: 8,
      title: 'Dictionaries and Tuples',
      description: 'Master more data structures',
      objectives: [
        'Work with dictionaries',
        'Understand tuples',
        'Know when to use each structure',
      ],
      outcomes: [
        'Store key-value pairs in dictionaries',
        'Use tuples for immutable sequences',
        'Choose the right data structure',
      ],
      topics: [
        'Creating dictionaries',
        'Dictionary methods',
        'Tuples and immutability',
        'Dictionary vs list vs tuple',
        'Nested data structures',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Dictionaries store key-value pairs, perfect for looking up values by name. Tuples are like lists but immutable (can\'t be changed). Each data structure has specific use cases, and knowing which to use makes you a better programmer.',
    },
    {
      id: 'python-day-9',
      day: 9,
      title: 'File Operations - Reading and Writing',
      description: 'Work with files on your system',
      objectives: [
        'Read from files',
        'Write to files',
        'Handle file errors safely',
      ],
      outcomes: [
        'Read and write text files',
        'Process file contents',
        'Handle file operations safely',
      ],
      topics: [
        'Opening and closing files',
        'Reading files',
        'Writing files',
        'With statements',
        'File paths and modes',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Most programs need to read or write files - configuration files, data files, logs, etc. Python makes file operations straightforward. The "with" statement ensures files are properly closed, even if errors occur.',
    },
    {
      id: 'python-day-10',
      day: 10,
      title: 'Error Handling - Try, Except, Finally',
      description: 'Handle errors gracefully',
      objectives: [
        'Understand exceptions',
        'Use try/except blocks',
        'Create robust programs',
      ],
      outcomes: [
        'Catch and handle errors',
        'Write error-resistant code',
        'Use finally for cleanup',
      ],
      topics: [
        'Exceptions in Python',
        'Try/except blocks',
        'Multiple except clauses',
        'Finally clause',
        'Raising exceptions',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Errors happen - users enter invalid input, files don\'t exist, networks fail. Error handling lets your programs respond gracefully instead of crashing. Try/except blocks catch errors and let you handle them appropriately.',
    },
    {
      id: 'python-day-11',
      day: 11,
      title: 'Object-Oriented Programming Basics',
      description: 'Introduction to OOP concepts',
      objectives: [
        'Understand classes and objects',
        'Create classes with methods',
        'Use inheritance',
      ],
      outcomes: [
        'Define custom classes',
        'Create and use objects',
        'Apply OOP principles',
      ],
      topics: [
        'Classes and objects',
        'Methods and attributes',
        'Constructors (__init__)',
        'Inheritance',
        'Encapsulation basics',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Object-oriented programming organizes code into objects that have both data (attributes) and behavior (methods). Classes are blueprints for objects. OOP makes code more organized, reusable, and easier to understand.',
    },
    {
      id: 'python-day-12',
      day: 12,
      title: 'Working with Modules and Packages',
      description: 'Use and create Python modules',
      objectives: [
        'Import and use modules',
        'Understand Python\'s standard library',
        'Create your own modules',
      ],
      outcomes: [
        'Use built-in Python modules',
        'Organize code into modules',
        'Install and use third-party packages',
      ],
      topics: [
        'Importing modules',
        'Standard library overview',
        'Creating modules',
        'Packages and __init__.py',
        'pip and third-party packages',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Python\'s standard library provides thousands of ready-to-use functions. Modules help organize code into separate files. Packages are collections of modules. Learning to use and create modules makes you much more productive.',
    },
    {
      id: 'python-day-13',
      day: 13,
      title: 'List Comprehensions and Generators',
      description: 'Write elegant, efficient Python',
      objectives: [
        'Master list comprehensions',
        'Understand generators',
        'Write Pythonic code',
      ],
      outcomes: [
        'Use comprehensions effectively',
        'Create memory-efficient generators',
        'Write more elegant Python',
      ],
      topics: [
        'List comprehensions',
        'Dictionary comprehensions',
        'Set comprehensions',
        'Generator expressions',
        'When to use each',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'List comprehensions provide a concise way to create lists. Generators produce values on-demand, saving memory. These features make Python code more elegant and efficient. They\'re essential for writing "Pythonic" code.',
    },
    {
      id: 'python-day-14',
      day: 14,
      title: 'Working with APIs and JSON',
      description: 'Connect to web services',
      objectives: [
        'Make HTTP requests',
        'Parse JSON data',
        'Work with APIs',
      ],
      outcomes: [
        'Fetch data from APIs',
        'Process JSON responses',
        'Build programs that use web services',
      ],
      topics: [
        'Requests library',
        'Making API calls',
        'Parsing JSON',
        'Handling API responses',
        'API authentication basics',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Most modern applications interact with web APIs to fetch data, send data, or use cloud services. Python makes this easy with the requests library. JSON is the standard format for API data, and Python handles it beautifully.',
    },
    {
      id: 'python-day-15',
      day: 15,
      title: 'Python for Outlier Success',
      description: 'Apply Python skills to Outlier assessments',
      objectives: [
        'Understand Outlier\'s Python requirements',
        'Practice assessment scenarios',
        'Master debugging and testing',
      ],
      outcomes: [
        'Write Python code for Outlier assessments',
        'Debug code efficiently',
        'Follow professional Python practices',
      ],
      topics: [
        'Python best practices for assessments',
        'Common assessment patterns',
        'Debugging techniques',
        'Code quality and readability',
        'Time management strategies',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'This final module prepares you specifically for Outlier Python assessments. You\'ll practice common problem types, learn debugging strategies, and master the coding style Outlier reviewers expect. You\'ll be ready to pass on your first attempt.',
    },
  ],
};

export const englishCourse: Course = {
  id: 'english-expert',
  title: 'English Expert Mastery',
  description: 'Master English proficiency from Grade 7 level to expert, including grammar, writing, reading comprehension, and video interview skills.',
  icon: '📖',
  color: 'from-green-500 to-emerald-500',
  totalDays: 15,
  difficulty: 'Grade 7 to Expert',
  modules: [
    {
      id: 'english-day-1',
      day: 1,
      title: 'Grammar Foundations - Sentence Structure and Parts of Speech',
      description: 'Master the fundamentals of English grammar',
      objectives: [
        'Understand sentence structure and components',
        'Learn all parts of speech',
        'Identify and correct common grammar errors',
      ],
      outcomes: [
        'Write grammatically correct sentences',
        'Identify parts of speech in any sentence',
        'Understand sentence structure and function',
      ],
      topics: [
        'Parts of speech: nouns, verbs, adjectives, adverbs, etc.',
        'Sentence structure: subjects, predicates, objects',
        'Simple, compound, and complex sentences',
        'Common grammar errors and corrections',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'English grammar is the system of rules that governs how words are arranged and used. Understanding grammar is essential for clear communication. Every sentence has a subject (who or what) and a predicate (what they\'re doing). Words are classified into parts of speech based on their function in the sentence.',
    },
    {
      id: 'english-day-2',
      day: 2,
      title: 'Punctuation and Capitalization Mastery',
      description: 'Master punctuation rules and capitalization',
      objectives: [
        'Learn all punctuation marks and their uses',
        'Understand capitalization rules',
        'Apply punctuation correctly in writing',
      ],
      outcomes: [
        'Use punctuation correctly in all contexts',
        'Apply capitalization rules consistently',
        'Improve writing clarity through proper punctuation',
      ],
      topics: [
        'Periods, commas, semicolons, colons',
        'Question marks, exclamation points, quotation marks',
        'Apostrophes, hyphens, dashes',
        'Capitalization rules',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Punctuation marks are symbols used to clarify meaning and separate ideas in writing. Proper punctuation makes writing easier to read and understand. Capitalization rules determine which letters should be uppercase. Mastering these rules is essential for professional writing.',
    },
    {
      id: 'english-day-3',
      day: 3,
      title: 'Paragraph Structure and Essay Organization',
      description: 'Write well-organized paragraphs and essays',
      objectives: [
        'Structure paragraphs effectively',
        'Write clear topic sentences',
        'Organize essays logically',
      ],
      outcomes: [
        'Write coherent paragraphs',
        'Structure essays with introduction, body, and conclusion',
        'Use transitions to connect ideas',
      ],
      topics: [
        'Topic sentences',
        'Supporting details',
        'Concluding sentences',
        'Essay structure',
        'Transition words and phrases',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Good writing is well-organized. Paragraphs should have a clear topic sentence, supporting details, and a conclusion. Essays need an introduction that states your thesis, body paragraphs that develop your ideas, and a conclusion that summarizes your points.',
    },
    {
      id: 'english-day-4',
      day: 4,
      title: 'Reading Comprehension Strategies',
      description: 'Improve your reading comprehension',
      objectives: [
        'Use active reading strategies',
        'Identify main ideas and details',
        'Make inferences from text',
      ],
      outcomes: [
        'Read more effectively',
        'Understand complex texts',
        'Answer comprehension questions accurately',
      ],
      topics: [
        'Active reading techniques',
        'Finding main ideas',
        'Identifying supporting details',
        'Making inferences',
        'Understanding author\'s purpose',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Good reading comprehension requires active engagement with text. Preview the text, ask questions, look for main ideas, note supporting details, and make inferences. These strategies help you understand and remember what you read.',
    },
    {
      id: 'english-day-5',
      day: 5,
      title: 'Vocabulary Building and Context Clues',
      description: 'Expand your vocabulary effectively',
      objectives: [
        'Learn vocabulary building strategies',
        'Use context clues to determine meaning',
        'Apply new vocabulary in writing',
      ],
      outcomes: [
        'Expand your vocabulary systematically',
        'Determine word meanings from context',
        'Use advanced vocabulary appropriately',
      ],
      topics: [
        'Word roots, prefixes, and suffixes',
        'Context clues',
        'Dictionary usage',
        'Vocabulary in writing',
        'Academic vocabulary',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'A strong vocabulary improves reading comprehension and writing quality. Learn words systematically through roots and affixes. Use context clues to figure out unfamiliar words. Practice using new vocabulary in your own writing.',
    },
    {
      id: 'english-day-6',
      day: 6,
      title: 'Common Grammar Mistakes and How to Fix Them',
      description: 'Eliminate common grammar errors',
      objectives: [
        'Identify frequent grammar mistakes',
        'Correct subject-verb agreement errors',
        'Fix pronoun problems',
      ],
      outcomes: [
        'Recognize and fix common errors',
        'Write grammatically correct sentences',
        'Self-edit effectively',
      ],
      topics: [
        'Subject-verb agreement',
        'Pronoun-antecedent agreement',
        'Misplaced modifiers',
        'Run-on sentences and fragments',
        'Comma splices',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Even good writers make mistakes. Common errors include subject-verb disagreement, pronoun problems, misplaced modifiers, and sentence fragments. Learning to spot and fix these errors improves your writing immediately.',
    },
    {
      id: 'english-day-7',
      day: 7,
      title: 'Persuasive Writing Techniques',
      description: 'Write convincing arguments',
      objectives: [
        'Understand persuasive writing structure',
        'Use rhetorical appeals effectively',
        'Support arguments with evidence',
      ],
      outcomes: [
        'Write persuasive essays',
        'Use logos, pathos, and ethos',
        'Counter opposing arguments',
      ],
      topics: [
        'Persuasive essay structure',
        'Rhetorical appeals (logos, pathos, ethos)',
        'Evidence and examples',
        'Counterarguments',
        'Persuasive language',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Persuasive writing convinces readers to accept your position. Use logical arguments (logos), emotional appeals (pathos), and establish credibility (ethos). Support claims with evidence, address counterarguments, and use persuasive language.',
    },
    {
      id: 'english-day-8',
      day: 8,
      title: 'Business Writing and Professional Communication',
      description: 'Master professional writing',
      objectives: [
        'Write professional emails',
        'Create business documents',
        'Use appropriate tone and formality',
      ],
      outcomes: [
        'Communicate professionally in writing',
        'Write clear, concise emails',
        'Adapt tone for different audiences',
      ],
      topics: [
        'Professional email writing',
        'Business letter format',
        'Memos and reports',
        'Tone and formality',
        'Proofreading techniques',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Professional writing is clear, concise, and appropriate for its audience. Emails should have clear subject lines, get to the point quickly, and use professional tone. Business documents follow specific formats. Always proofread before sending.',
    },
    {
      id: 'english-day-9',
      day: 9,
      title: 'Critical Analysis and Analytical Writing',
      description: 'Analyze and evaluate texts critically',
      objectives: [
        'Read texts critically',
        'Write analytical essays',
        'Support analysis with evidence',
      ],
      outcomes: [
        'Analyze texts deeply',
        'Write clear analytical essays',
        'Evaluate arguments critically',
      ],
      topics: [
        'Critical reading strategies',
        'Analytical essay structure',
        'Literary analysis',
        'Evaluating arguments',
        'Close reading techniques',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Critical analysis goes beyond understanding what a text says to examining how and why it says it. Analytical writing breaks down texts, examines their components, and evaluates their effectiveness. Support your analysis with specific evidence.',
    },
    {
      id: 'english-day-10',
      day: 10,
      title: 'Research Skills and Citation',
      description: 'Conduct research and cite sources properly',
      objectives: [
        'Find credible sources',
        'Integrate sources in writing',
        'Cite sources correctly',
      ],
      outcomes: [
        'Evaluate source credibility',
        'Use sources to support arguments',
        'Avoid plagiarism through proper citation',
      ],
      topics: [
        'Finding credible sources',
        'Evaluating sources',
        'Paraphrasing and summarizing',
        'MLA and APA citation',
        'Avoiding plagiarism',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Research writing requires finding credible sources, integrating them smoothly, and citing them properly. Learn to evaluate sources for reliability, paraphrase without plagiarizing, and use MLA or APA citation format correctly.',
    },
    {
      id: 'english-day-11',
      day: 11,
      title: 'Advanced Grammar - Complex Sentences',
      description: 'Master complex sentence structures',
      objectives: [
        'Write complex and compound-complex sentences',
        'Use subordination effectively',
        'Vary sentence structure',
      ],
      outcomes: [
        'Write sophisticated sentences',
        'Use subordinate clauses correctly',
        'Improve writing flow and rhythm',
      ],
      topics: [
        'Independent and dependent clauses',
        'Subordinating conjunctions',
        'Relative clauses',
        'Sentence variety',
        'Avoiding awkward constructions',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Advanced writing uses varied sentence structures. Complex sentences combine independent and dependent clauses to show relationships between ideas. Subordination helps emphasize important information. Varied sentence length and structure makes writing more engaging.',
    },
    {
      id: 'english-day-12',
      day: 12,
      title: 'Editing and Revision Strategies',
      description: 'Improve your writing through revision',
      objectives: [
        'Develop effective revision strategies',
        'Edit for clarity and conciseness',
        'Polish writing to professional quality',
      ],
      outcomes: [
        'Revise writing systematically',
        'Edit effectively at multiple levels',
        'Produce polished final drafts',
      ],
      topics: [
        'Revision vs. editing',
        'Content and organization revision',
        'Sentence-level editing',
        'Proofreading techniques',
        'Peer review',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Good writing is rewriting. Revision improves content and organization. Editing fixes sentence-level problems. Proofreading catches final errors. Learn to revise systematically, working from large-scale issues down to small details.',
    },
    {
      id: 'english-day-13',
      day: 13,
      title: 'Speaking and Presentation Skills',
      description: 'Communicate effectively orally',
      objectives: [
        'Organize effective presentations',
        'Speak clearly and confidently',
        'Handle Q&A sessions',
      ],
      outcomes: [
        'Deliver confident presentations',
        'Organize ideas for oral delivery',
        'Answer questions effectively',
      ],
      topics: [
        'Presentation structure',
        'Speaking techniques',
        'Visual aids',
        'Handling nerves',
        'Q&A strategies',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Effective oral communication requires organization, confidence, and clarity. Structure presentations with clear introduction, body, and conclusion. Practice to build confidence. Use visual aids to support, not replace, your message.',
    },
    {
      id: 'english-day-14',
      day: 14,
      title: 'Video Interview Communication Skills',
      description: 'Master video interview techniques',
      objectives: [
        'Prepare for video interviews',
        'Communicate effectively on camera',
        'Answer questions professionally',
      ],
      outcomes: [
        'Present professionally on video',
        'Answer interview questions clearly',
        'Make strong impressions in video interviews',
      ],
      topics: [
        'Video interview preparation',
        'On-camera presence',
        'Answering behavioral questions',
        'Technical setup',
        'Professional communication',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Video interviews require special skills. Set up proper lighting and background. Look at the camera. Speak clearly and confidently. Prepare for common questions. Practice until video communication feels natural.',
    },
    {
      id: 'english-day-15',
      day: 15,
      title: 'English for Outlier Success',
      description: 'Apply English skills to Outlier assessments',
      objectives: [
        'Understand Outlier\'s English requirements',
        'Practice assessment scenarios',
        'Master professional communication',
      ],
      outcomes: [
        'Communicate professionally for Outlier',
        'Write clearly under time pressure',
        'Excel in video interviews',
      ],
      topics: [
        'Outlier communication standards',
        'Assessment writing strategies',
        'Video interview best practices',
        'Professional English usage',
        'Time management for assessments',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'This final module prepares you for Outlier\'s English requirements. You\'ll practice writing clearly under pressure, communicating professionally in video interviews, and using English at the level Outlier expects. You\'ll be ready to pass assessments confidently.',
    },
  ],
};

export const outlierTipsCourse: Course = {
  id: 'outlier-tips',
  title: 'Outlier Assessment Playbook',
  description: 'Master the Outlier assessment format, scoring methodology, and proven strategies to pass on your first attempt.',
  icon: '🎯',
  color: 'from-purple-500 to-pink-500',
  totalDays: 1,
  difficulty: 'All Levels',
  modules: [
    {
      id: 'outlier-tips-1',
      day: 1,
      title: 'Understanding Outlier Assessments',
      description: 'Complete guide to Outlier assessment structure and scoring',
      objectives: [
        'Understand Outlier.ai assessment format',
        'Learn the scoring methodology',
        'Identify high-frequency test topics',
      ],
      outcomes: [
        'Explain the complete assessment structure',
        'Understand how Outlier scores your responses',
        'Know what assessors are looking for',
      ],
      topics: [
        'Assessment structure breakdown',
        'Scoring methodology (40% correctness, 25% quality, 15% efficiency, 10% completeness, 10% explanation)',
        'Multiple choice vs coding challenges vs code review',
        'Common mistakes that cause failures',
        '12 proven strategies to pass',
        'Time management techniques',
        'How to structure responses for maximum points',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'This comprehensive guide reveals exactly how Outlier.ai assessments work, what they\'re looking for, and the proven strategies used by successful candidates. Learn the scoring rubric, common pitfalls, and insider tips from assessment experts.',
    },
    {
      id: 'outlier-tips-2',
      day: 1,
      title: '12 Proven Strategies to Pass',
      description: 'Expert strategies used by successful Outlier contractors',
      objectives: [
        'Learn 12 proven passing strategies',
        'Understand assessment day preparation',
        'Master response structuring techniques',
      ],
      outcomes: [
        'Apply strategies to improve assessment performance',
        'Prepare effectively for assessment day',
        'Structure responses for maximum scoring',
      ],
      topics: [
        'Strategy 1: Understand role requirements',
        'Strategy 2: Set up environment properly',
        'Strategy 3: Review fundamentals strategically',
        'Strategy 4: Practice under time pressure',
        'Strategy 5: Read instructions carefully',
        'Strategy 6: Plan before you code',
        'Strategy 7: Write clean, readable code',
        'Strategy 8: Handle edge cases',
        'Strategy 9: Use error handling appropriately',
        'Strategy 10: Test your code thoroughly',
        'Strategy 11: Manage your time effectively',
        'Strategy 12: Write helpful comments',
      ],
      duration: '1-2 hours',
      difficulty: 'Beginner',
      content: 'These 12 strategies are used by top-performing Outlier contractors to consistently pass assessments and unlock higher-paying projects. Each strategy includes detailed explanations, real examples, and practical implementation tips.',
    },
  ],
};

export const oneDayCourse: Course = {
  id: 'one-day-course',
  title: '2-Day Outlier Crash Course',
  description: 'Quick introduction to Git, Python, and English fundamentals. Get started with the essentials in just 2 days.',
  icon: '⚡',
  color: 'from-yellow-500 to-orange-500',
  totalDays: 2,
  difficulty: 'Beginner',
  modules: [
    {
      id: 'one-day-1',
      day: 1,
      title: 'Git & Python Fundamentals',
      description: 'Quick introduction to Git version control and Python basics',
      objectives: [
        'Understand Git basics and why it matters',
        'Write your first Python program',
        'Learn essential Git and Python commands',
      ],
      outcomes: [
        'Create and manage a Git repository',
        'Write simple Python programs',
        'Understand version control basics',
      ],
      topics: [
        'What is Git and why developers use it',
        'Basic Git commands: init, add, commit, push',
        'Introduction to Python',
        'Variables and data types',
        'Writing your first program',
      ],
      duration: '4-5 hours',
      difficulty: 'Beginner',
      content: 'This crash course covers the absolute essentials of Git and Python. You\'ll learn what Git is, why it\'s important, and how to use basic commands. You\'ll also write your first Python program and understand fundamental concepts like variables and data types.',
    },
    {
      id: 'one-day-2',
      day: 2,
      title: 'English Communication Essentials',
      description: 'Master essential English skills for professional communication',
      objectives: [
        'Understand English grammar fundamentals',
        'Write clear, professional sentences',
        'Communicate effectively in writing',
      ],
      outcomes: [
        'Write grammatically correct sentences',
        'Communicate professionally in writing',
        'Understand basic punctuation and capitalization',
      ],
      topics: [
        'Parts of speech and sentence structure',
        'Common grammar errors and corrections',
        'Punctuation and capitalization',
        'Writing clear, concise sentences',
        'Professional communication tips',
      ],
      duration: '4-5 hours',
      difficulty: 'Beginner',
      content: 'Learn the essentials of English grammar and professional communication. This module covers the most important grammar rules, common mistakes, and practical tips for writing clearly and professionally.',
    },
  ],
};

export const allCourses: Course[] = [outlierTipsCourse, oneDayCourse, gitCourse, pythonCourse, englishCourse];

export const getCourseById = (id: string): Course | undefined => {
  return allCourses.find(course => course.id === id);
};

export const getCourseTier = (courseId: string): 'lead-magnet' | 'upsell' | 'core' => {
  if (courseId === 'outlier-tips') return 'lead-magnet';
  if (courseId === 'one-day-course') return 'upsell';
  return 'core';
};

export const getModuleById = (courseId: string, moduleId: string): Module | undefined => {
  const course = getCourseById(courseId);
  return course?.modules.find(module => module.id === moduleId);
};

export const getFreeCourses = (): Course[] => {
  return [outlierTipsCourse, oneDayCourse];
};

export const getPaidCourses = (): Course[] => {
  return [gitCourse, pythonCourse, englishCourse];
};
