export interface Module {
  id: string;
  day: number;
  title: string;
  description: string;
  objectives: string[];
  outcomes: string[];
  topics: string[];
  duration: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  content: string;
}

export interface Course {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  modules: Module[];
  totalDays: number;
  difficulty: string;
}

export const gitCourse: Course = {
  id: 'git-expert',
  title: 'Git Expert Mastery',
  description: 'Master Git version control and become an expert in repository management, branching strategies, and collaboration workflows.',
  icon: '📚',
  color: 'from-orange-500 to-red-500',
  totalDays: 15,
  difficulty: 'Beginner to Advanced',
  modules: [
    {
      id: 'git-day-1',
      day: 1,
      title: 'What is Git and Why It Matters',
      description: 'Introduction to version control and Git fundamentals',
      objectives: [
        'Understand what Git is and why it\'s essential',
        'Learn the history and philosophy of Git',
        'Understand the difference between Git and GitHub',
      ],
      outcomes: [
        'Explain Git\'s purpose in software development',
        'Identify key Git concepts and terminology',
        'Understand when and why to use version control',
      ],
      topics: [
        'What is version control?',
        'Git vs other version control systems',
        'Git workflow overview',
        'Key Git concepts: repositories, commits, branches',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Git is a distributed version control system that tracks changes in your code. It allows multiple developers to work on the same project without conflicts, maintains a complete history of all changes, and enables easy collaboration. Git is essential for professional software development and is used by virtually every tech company in the world.',
    },
    {
      id: 'git-day-2',
      day: 2,
      title: 'Setting Up Your First Git Environment',
      description: 'Install and configure Git for your system',
      objectives: [
        'Install Git on your operating system',
        'Configure Git with your identity',
        'Create your first repository',
      ],
      outcomes: [
        'Successfully install and configure Git',
        'Create and initialize a Git repository',
        'Understand basic Git configuration',
      ],
      topics: [
        'Installing Git on Windows, Mac, and Linux',
        'Configuring user name and email',
        'Creating your first repository',
        'Understanding .git directory',
      ],
      duration: '1-2 hours',
      difficulty: 'Beginner',
      content: 'Setting up Git involves installing it on your system and configuring it with your user information. This configuration is important because every commit you make will be attributed to this identity. Once configured, you can initialize a new repository or clone an existing one to start working with Git.',
    },
    {
      id: 'git-day-3',
      day: 3,
      title: 'Repositories and Basic Commits',
      description: 'Learn how to create repositories and make commits',
      objectives: [
        'Create and initialize Git repositories',
        'Stage and commit changes',
        'Write meaningful commit messages',
      ],
      outcomes: [
        'Initialize new Git repositories',
        'Stage files and create commits',
        'Follow commit message best practices',
      ],
      topics: [
        'git init and git clone',
        'git add and staging area',
        'git commit and commit messages',
        'Viewing commit history with git log',
        'Best practices for commit messages',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Commits are snapshots of your project at a specific point in time. Learning to make clear, atomic commits with descriptive messages is fundamental to using Git effectively. The staging area allows you to carefully craft each commit to include only the changes you want.',
    },
    {
      id: 'git-day-4',
      day: 4,
      title: 'Branching - Creating Parallel Work Paths',
      description: 'Master Git branching for parallel development',
      objectives: [
        'Understand Git branching concepts',
        'Create and switch between branches',
        'Develop features in isolation',
      ],
      outcomes: [
        'Create new branches for features',
        'Switch between branches confidently',
        'Understand branch naming conventions',
      ],
      topics: [
        'What are branches and why use them',
        'Creating branches with git branch',
        'Switching branches with git checkout/switch',
        'Branch naming conventions',
        'Listing and viewing branches',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Branches allow you to work on different features or experiments without affecting the main codebase. They are lightweight in Git, making it easy to create and delete them as needed. Proper branch management is key to collaborative development.',
    },
    {
      id: 'git-day-5',
      day: 5,
      title: 'Merging - Bringing Work Together',
      description: 'Learn how to merge branches and integrate changes',
      objectives: [
        'Understand different merge strategies',
        'Perform basic merges',
        'Recognize merge conflicts',
      ],
      outcomes: [
        'Merge branches successfully',
        'Choose appropriate merge strategies',
        'Understand when conflicts occur',
      ],
      topics: [
        'git merge basics',
        'Fast-forward vs three-way merges',
        'Merge strategies',
        'Introduction to merge conflicts',
        'Viewing merged branches',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Merging integrates changes from one branch into another. Git offers different merge strategies depending on the situation. Understanding these strategies and when to use them is crucial for maintaining a clean project history.',
    },
    {
      id: 'git-day-6',
      day: 6,
      title: 'Undoing Changes and Time Travel',
      description: 'Learn to undo changes and navigate Git history',
      objectives: [
        'Undo changes with git reset and revert',
        'Recover lost commits',
        'Navigate Git history effectively',
      ],
      outcomes: [
        'Safely undo commits and changes',
        'Recover from mistakes',
        'Use git reflog for history navigation',
      ],
      topics: [
        'git reset --soft, --mixed, --hard',
        'git revert for safe undoing',
        'git checkout for file restoration',
        'git reflog for recovery',
        'Understanding HEAD and references',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Mistakes happen, and Git provides powerful tools to undo them. Understanding the difference between reset, revert, and checkout is essential. Git reflog acts as a safety net, allowing you to recover seemingly lost work.',
    },
    {
      id: 'git-day-7',
      day: 7,
      title: 'Remote Repositories and GitHub Basics',
      description: 'Connect to remote repositories and collaborate online',
      objectives: [
        'Understand remote repositories',
        'Push and pull changes',
        'Work with GitHub',
      ],
      outcomes: [
        'Connect local repos to remote',
        'Push and pull changes effectively',
        'Set up GitHub repositories',
      ],
      topics: [
        'Understanding remotes',
        'git remote add and configuration',
        'git push and git pull',
        'Setting up SSH keys',
        'GitHub repository setup',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Remote repositories enable collaboration by hosting your code online. GitHub, GitLab, and Bitbucket are popular platforms. Learning to push and pull changes is fundamental to working with remote repositories.',
    },
    {
      id: 'git-day-8',
      day: 8,
      title: 'Collaboration Workflows and Pull Requests',
      description: 'Master collaborative development workflows',
      objectives: [
        'Understand pull request workflow',
        'Collaborate effectively with teams',
        'Review code professionally',
      ],
      outcomes: [
        'Create and manage pull requests',
        'Review code effectively',
        'Follow collaborative workflows',
      ],
      topics: [
        'Fork and pull request workflow',
        'Creating pull requests on GitHub',
        'Code review best practices',
        'Branch protection rules',
        'Collaborative Git workflows',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Pull requests are the standard way to propose changes in collaborative projects. They facilitate code review, discussion, and quality control before changes are merged. Understanding this workflow is essential for professional development.',
    },
    {
      id: 'git-day-9',
      day: 9,
      title: 'Resolving Conflicts Like a Pro',
      description: 'Master merge conflict resolution techniques',
      objectives: [
        'Understand why conflicts occur',
        'Resolve conflicts manually',
        'Use tools to assist conflict resolution',
      ],
      outcomes: [
        'Confidently resolve merge conflicts',
        'Use conflict markers effectively',
        'Prevent conflicts when possible',
      ],
      topics: [
        'Understanding conflict markers',
        'Manual conflict resolution',
        'Using merge tools',
        'Strategies to minimize conflicts',
        'Testing after conflict resolution',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Merge conflicts occur when Git cannot automatically reconcile differences between branches. While they can be intimidating, conflicts are a normal part of collaborative development. Learning to resolve them efficiently is a crucial skill.',
    },
    {
      id: 'git-day-10',
      day: 10,
      title: 'Git History and Advanced Viewing',
      description: 'Master Git history navigation and visualization',
      objectives: [
        'Use git log effectively',
        'Filter and search Git history',
        'Visualize branch history',
      ],
      outcomes: [
        'Navigate Git history efficiently',
        'Find specific commits quickly',
        'Use advanced log options',
      ],
      topics: [
        'Advanced git log options',
        'Filtering by author, date, and content',
        'git log --graph for visualization',
        'git show for detailed views',
        'git blame for line history',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Git maintains a complete history of your project. Learning to navigate this history effectively helps you understand how your project evolved, find when bugs were introduced, and track down specific changes.',
    },
    {
      id: 'git-day-11',
      day: 11,
      title: 'Rebasing and Advanced Branch Management',
      description: 'Master rebasing for clean project history',
      objectives: [
        'Understand rebasing vs merging',
        'Perform interactive rebases',
        'Maintain clean Git history',
      ],
      outcomes: [
        'Use rebase to clean up history',
        'Perform interactive rebases',
        'Know when to rebase vs merge',
      ],
      topics: [
        'git rebase basics',
        'Interactive rebase with -i',
        'Squashing commits',
        'Rewriting commit history',
        'When to avoid rebasing',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Rebasing is a powerful tool for maintaining a clean, linear project history. Interactive rebasing allows you to edit, reorder, squash, and split commits. However, rebasing rewrites history, so it must be used carefully, especially with shared branches.',
    },
    {
      id: 'git-day-12',
      day: 12,
      title: 'Stashing, Cherry-picking, and Selective Commits',
      description: 'Master advanced Git techniques for flexible workflow',
      objectives: [
        'Use git stash for temporary changes',
        'Cherry-pick commits between branches',
        'Create selective commits',
      ],
      outcomes: [
        'Stash and apply changes effectively',
        'Cherry-pick specific commits',
        'Use git add -p for partial staging',
      ],
      topics: [
        'git stash save and apply',
        'Managing multiple stashes',
        'git cherry-pick for selective merging',
        'git add -p for interactive staging',
        'Creating atomic commits',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'These advanced techniques provide flexibility in your Git workflow. Stashing allows you to save work-in-progress temporarily, cherry-picking lets you apply specific commits to other branches, and interactive staging helps create precise commits.',
    },
    {
      id: 'git-day-13',
      day: 13,
      title: 'Tags, Releases, and Version Management',
      description: 'Learn to mark important points in project history',
      objectives: [
        'Create and manage Git tags',
        'Understand semantic versioning',
        'Create releases on GitHub',
      ],
      outcomes: [
        'Tag releases appropriately',
        'Follow semantic versioning',
        'Manage project versions',
      ],
      topics: [
        'Lightweight vs annotated tags',
        'Creating and pushing tags',
        'Semantic versioning (SemVer)',
        'GitHub releases',
        'Version management strategies',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Tags mark important points in your project history, typically releases. Understanding semantic versioning and proper release management is crucial for maintaining stable software and communicating changes to users.',
    },
    {
      id: 'git-day-14',
      day: 14,
      title: 'Advanced Workflows and Best Practices',
      description: 'Master professional Git workflows and patterns',
      objectives: [
        'Understand Git Flow and other workflows',
        'Implement best practices',
        'Optimize team collaboration',
      ],
      outcomes: [
        'Choose appropriate workflows',
        'Follow industry best practices',
        'Collaborate effectively in teams',
      ],
      topics: [
        'Git Flow workflow',
        'GitHub Flow workflow',
        'Trunk-based development',
        'Best practices for commit messages',
        'Code review strategies',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Different teams use different Git workflows depending on their needs. Understanding popular workflows like Git Flow and GitHub Flow helps you adapt to various team environments. Consistent best practices ensure smooth collaboration.',
    },
    {
      id: 'git-day-15',
      day: 15,
      title: 'Real-World Scenarios and Assessment Preparation',
      description: 'Apply your Git knowledge to real scenarios',
      objectives: [
        'Solve complex Git scenarios',
        'Prepare for assessments',
        'Apply cumulative knowledge',
      ],
      outcomes: [
        'Handle real-world Git challenges',
        'Pass Git proficiency assessments',
        'Demonstrate expert-level understanding',
      ],
      topics: [
        'Common Git problems and solutions',
        'Assessment preparation strategies',
        'Real-world collaboration scenarios',
        'Debugging Git issues',
        'Performance optimization',
      ],
      duration: '3-4 hours',
      difficulty: 'Advanced',
      content: 'This final module brings together everything you\'ve learned, presenting real-world scenarios and assessment-style challenges. You\'ll practice solving complex Git problems and demonstrate your mastery of version control.',
    },
  ],
};

export const pythonCourse: Course = {
  id: 'python-expert',
  title: 'Python Expert Mastery',
  description: 'Master Python programming from basics to advanced techniques, including OOP, data structures, and professional development practices.',
  icon: '🐍',
  color: 'from-blue-500 to-cyan-500',
  totalDays: 15,
  difficulty: 'Beginner to Advanced',
  modules: [
    {
      id: 'python-day-1',
      day: 1,
      title: 'What is Python and Your First Program',
      description: 'Introduction to Python and writing your first program',
      objectives: [
        'Understand what Python is and its uses',
        'Install Python on your system',
        'Write and run your first Python program',
      ],
      outcomes: [
        'Explain Python\'s purpose and popularity',
        'Install Python and verify installation',
        'Write a simple "Hello, World!" program',
      ],
      topics: [
        'What is Python?',
        'Why Python is popular',
        'Installing Python',
        'Running Python code',
        'Your first program: print()',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Python is a high-level, interpreted programming language known for its simplicity and readability. It\'s used in web development, data science, artificial intelligence, automation, and many other fields. Python\'s syntax is designed to be intuitive, making it an excellent language for beginners while remaining powerful enough for professionals.',
    },
    {
      id: 'python-day-2',
      day: 2,
      title: 'Variables, Data Types, and Basic Operations',
      description: 'Learn about variables, data types, and performing calculations',
      objectives: [
        'Understand variables and naming conventions',
        'Learn Python\'s basic data types',
        'Perform mathematical operations',
      ],
      outcomes: [
        'Create and use variables correctly',
        'Identify and work with different data types',
        'Perform calculations and string operations',
      ],
      topics: [
        'Variables and assignment',
        'Data types: strings, integers, floats, booleans',
        'Type conversion',
        'Mathematical operations',
        'String manipulation',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Variables are containers for storing data values. Python supports several basic data types including strings (text), integers (whole numbers), floats (decimal numbers), and booleans (True/False). Understanding these types and how to work with them is fundamental to programming in Python.',
    },
    {
      id: 'python-day-3',
      day: 3,
      title: 'Control Flow - Conditionals and Loops',
      description: 'Master decision-making and iteration in Python',
      objectives: [
        'Use if/elif/else statements',
        'Implement for and while loops',
        'Understand control flow logic',
      ],
      outcomes: [
        'Write conditional statements',
        'Implement loops effectively',
        'Control program flow',
      ],
      topics: [
        'if, elif, else statements',
        'Comparison and logical operators',
        'for loops and iteration',
        'while loops',
        'break and continue statements',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Control flow structures allow your programs to make decisions and repeat actions. Conditionals (if/elif/else) let you execute different code based on conditions, while loops (for/while) enable repetitive tasks. Mastering control flow is essential for writing dynamic programs.',
    },
    {
      id: 'python-day-4',
      day: 4,
      title: 'Functions and Scope',
      description: 'Learn to create reusable code with functions',
      objectives: [
        'Define and call functions',
        'Understand parameters and return values',
        'Master variable scope',
      ],
      outcomes: [
        'Create well-structured functions',
        'Use parameters and returns effectively',
        'Understand local vs global scope',
      ],
      topics: [
        'Defining functions with def',
        'Function parameters and arguments',
        'Return statements',
        'Variable scope (local vs global)',
        'Lambda functions',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Functions are reusable blocks of code that perform specific tasks. They help organize your code, make it more readable, and reduce repetition. Understanding parameters, return values, and variable scope is crucial for writing maintainable Python code.',
    },
    {
      id: 'python-day-5',
      day: 5,
      title: 'Lists, Tuples, and Sets',
      description: 'Master Python\'s sequence data structures',
      objectives: [
        'Work with lists and list methods',
        'Understand tuples and immutability',
        'Use sets for unique collections',
      ],
      outcomes: [
        'Manipulate lists effectively',
        'Choose appropriate data structures',
        'Perform set operations',
      ],
      topics: [
        'Creating and accessing lists',
        'List methods (append, extend, pop, etc.)',
        'Tuples and immutability',
        'Sets and set operations',
        'List slicing',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Lists, tuples, and sets are fundamental data structures in Python. Lists are mutable sequences perfect for ordered collections. Tuples are immutable and used for data that shouldn\'t change. Sets store unique elements and support mathematical set operations.',
    },
    {
      id: 'python-day-6',
      day: 6,
      title: 'Dictionaries and Data Structures',
      description: 'Master key-value pairs and complex data structures',
      objectives: [
        'Create and manipulate dictionaries',
        'Access and modify dictionary data',
        'Work with nested data structures',
      ],
      outcomes: [
        'Use dictionaries effectively',
        'Handle complex nested structures',
        'Choose appropriate data structures',
      ],
      topics: [
        'Creating dictionaries',
        'Accessing and modifying dictionary data',
        'Dictionary methods',
        'Nested data structures',
        'Dictionary comprehensions',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Dictionaries store data as key-value pairs, making them perfect for representing structured information. They\'re one of Python\'s most powerful data structures, offering fast lookups and flexible data organization. Understanding dictionaries is essential for real-world Python programming.',
    },
    {
      id: 'python-day-7',
      day: 7,
      title: 'String Manipulation and Formatting',
      description: 'Master string operations and formatting techniques',
      objectives: [
        'Perform string operations',
        'Format strings effectively',
        'Process text data',
      ],
      outcomes: [
        'Manipulate strings confidently',
        'Use modern formatting techniques',
        'Process text efficiently',
      ],
      topics: [
        'String methods (split, join, replace, etc.)',
        'String formatting (f-strings, format())',
        'String slicing and indexing',
        'Regular expressions basics',
        'Working with text files',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Strings are everywhere in programming. Python offers powerful tools for manipulating text, from basic operations to advanced formatting with f-strings. Learning to work with strings effectively is crucial for data processing, user interfaces, and file operations.',
    },
    {
      id: 'python-day-8',
      day: 8,
      title: 'File Handling and I/O Operations',
      description: 'Learn to read from and write to files',
      objectives: [
        'Read and write text files',
        'Handle file operations safely',
        'Process file data',
      ],
      outcomes: [
        'Perform file I/O operations',
        'Use context managers properly',
        'Handle file exceptions',
      ],
      topics: [
        'Opening and closing files',
        'Reading file content',
        'Writing to files',
        'Context managers (with statement)',
        'Working with CSV and JSON files',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'File handling is essential for persisting data and processing external information. Python makes file operations straightforward with built-in functions and context managers. Understanding proper file handling prevents data loss and resource leaks.',
    },
    {
      id: 'python-day-9',
      day: 9,
      title: 'Object-Oriented Programming Basics',
      description: 'Introduction to OOP concepts in Python',
      objectives: [
        'Understand OOP principles',
        'Create classes and objects',
        'Use instance and class variables',
      ],
      outcomes: [
        'Define classes effectively',
        'Create and use objects',
        'Understand OOP benefits',
      ],
      topics: [
        'Classes and objects',
        'Instance variables and methods',
        'The __init__ constructor',
        'self parameter',
        'Class vs instance variables',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Object-Oriented Programming (OOP) is a programming paradigm that organizes code around objects and classes. It promotes code reusability, modularity, and maintainability. Understanding OOP is crucial for writing professional Python applications.',
    },
    {
      id: 'python-day-10',
      day: 10,
      title: 'Classes, Objects, and Inheritance',
      description: 'Master advanced OOP concepts',
      objectives: [
        'Implement inheritance',
        'Use polymorphism',
        'Understand method overriding',
      ],
      outcomes: [
        'Create class hierarchies',
        'Override methods appropriately',
        'Apply OOP principles',
      ],
      topics: [
        'Inheritance and parent classes',
        'Method overriding',
        'super() function',
        'Multiple inheritance',
        'Abstract classes',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Inheritance allows classes to inherit attributes and methods from other classes, promoting code reuse. Polymorphism enables objects of different classes to be treated uniformly. These concepts are fundamental to advanced Python programming.',
    },
    {
      id: 'python-day-11',
      day: 11,
      title: 'Modules and Packages',
      description: 'Learn to organize code with modules and packages',
      objectives: [
        'Create and import modules',
        'Organize code into packages',
        'Use Python\'s standard library',
      ],
      outcomes: [
        'Structure projects effectively',
        'Import modules properly',
        'Use standard library modules',
      ],
      topics: [
        'Creating modules',
        'Importing modules and functions',
        'Package structure',
        'The __init__.py file',
        'Popular standard library modules',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Modules and packages help organize code into manageable, reusable components. Python\'s standard library provides numerous modules for common tasks. Learning to structure projects with modules and packages is essential for large applications.',
    },
    {
      id: 'python-day-12',
      day: 12,
      title: 'Error Handling and Exceptions',
      description: 'Master exception handling for robust programs',
      objectives: [
        'Understand Python exceptions',
        'Implement try/except blocks',
        'Create custom exceptions',
      ],
      outcomes: [
        'Handle errors gracefully',
        'Write robust code',
        'Debug effectively',
      ],
      topics: [
        'Try/except/finally blocks',
        'Common exception types',
        'Raising exceptions',
        'Custom exceptions',
        'Best practices for error handling',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Errors are inevitable in programming. Python\'s exception handling mechanism allows you to anticipate and handle errors gracefully. Proper error handling makes your programs more robust and user-friendly.',
    },
    {
      id: 'python-day-13',
      day: 13,
      title: 'List Comprehensions and Generators',
      description: 'Master Pythonic ways to create and iterate collections',
      objectives: [
        'Write list comprehensions',
        'Use generator expressions',
        'Understand iterators',
      ],
      outcomes: [
        'Create concise, readable code',
        'Use memory-efficient generators',
        'Apply Pythonic patterns',
      ],
      topics: [
        'List comprehensions',
        'Dictionary and set comprehensions',
        'Generator expressions',
        'Iterators and the iter() function',
        'Memory efficiency considerations',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'List comprehensions provide a concise way to create lists, making code more readable and often faster. Generators allow lazy evaluation, processing items one at a time for memory efficiency. These are hallmarks of Pythonic code.',
    },
    {
      id: 'python-day-14',
      day: 14,
      title: 'Python Best Practices and PEP 8',
      description: 'Learn Python coding standards and best practices',
      objectives: [
        'Follow PEP 8 style guide',
        'Write clean, maintainable code',
        'Apply Python idioms',
      ],
      outcomes: [
        'Write professional Python code',
        'Follow community standards',
        'Produce readable code',
      ],
      topics: [
        'PEP 8 style guide',
        'Naming conventions',
        'Code organization',
        'Documentation and docstrings',
        'Python idioms and patterns',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'PEP 8 is Python\'s official style guide, promoting consistent, readable code across the community. Following best practices and Python idioms makes your code more maintainable and professional. These standards are expected in professional environments.',
    },
    {
      id: 'python-day-15',
      day: 15,
      title: 'Real-World Projects and Assessment Prep',
      description: 'Apply Python skills to practical projects',
      objectives: [
        'Build complete Python programs',
        'Apply cumulative knowledge',
        'Prepare for assessments',
      ],
      outcomes: [
        'Create functional Python applications',
        'Demonstrate Python proficiency',
        'Pass Python assessments',
      ],
      topics: [
        'Project planning and structure',
        'Integrating multiple concepts',
        'Testing and debugging',
        'Assessment strategies',
        'Common interview questions',
      ],
      duration: '3-4 hours',
      difficulty: 'Advanced',
      content: 'This final module brings together all Python concepts through practical projects. You\'ll build complete applications, demonstrating your mastery of Python fundamentals and advanced features. Ideal preparation for Python proficiency assessments.',
    },
  ],
};

export const englishCourse: Course = {
  id: 'english-expert',
  title: 'English Expert Mastery',
  description: 'Master English proficiency from Grade 7 level to expert, including grammar, writing, reading comprehension, and video interview skills.',
  icon: '📖',
  color: 'from-green-500 to-emerald-500',
  totalDays: 15,
  difficulty: 'Grade 7 to Expert',
  modules: [
    {
      id: 'english-day-1',
      day: 1,
      title: 'Grammar Foundations - Sentence Structure and Parts of Speech',
      description: 'Master the fundamentals of English grammar',
      objectives: [
        'Understand sentence structure and components',
        'Learn all parts of speech',
        'Identify and correct common grammar errors',
      ],
      outcomes: [
        'Write grammatically correct sentences',
        'Identify parts of speech in any sentence',
        'Understand sentence structure and function',
      ],
      topics: [
        'Parts of speech: nouns, verbs, adjectives, adverbs, etc.',
        'Sentence structure: subjects, predicates, objects',
        'Simple, compound, and complex sentences',
        'Common grammar errors and corrections',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'English grammar is the system of rules that governs how words are arranged and used. Understanding grammar is essential for clear communication. Every sentence has a subject (who or what) and a predicate (what they\'re doing). Words are classified into parts of speech based on their function in the sentence.',
    },
    {
      id: 'english-day-2',
      day: 2,
      title: 'Punctuation and Capitalization Mastery',
      description: 'Master punctuation rules and capitalization',
      objectives: [
        'Learn all punctuation marks and their uses',
        'Understand capitalization rules',
        'Apply punctuation correctly in writing',
      ],
      outcomes: [
        'Use punctuation correctly in all contexts',
        'Apply capitalization rules consistently',
        'Improve writing clarity through proper punctuation',
      ],
      topics: [
        'Periods, commas, semicolons, colons',
        'Question marks, exclamation points, quotation marks',
        'Apostrophes, hyphens, dashes',
        'Capitalization rules',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Punctuation marks are symbols used to clarify meaning and separate ideas in writing. Proper punctuation makes writing easier to read and understand. Capitalization rules determine which letters should be uppercase. Mastering these rules is essential for professional writing.',
    },
    {
      id: 'english-day-3',
      day: 3,
      title: 'Punctuation Mastery',
      description: 'Master all punctuation marks and their correct usage',
      objectives: [
        'Use commas, periods, and semicolons correctly',
        'Master apostrophes and quotation marks',
        'Apply punctuation in complex sentences',
      ],
      outcomes: [
        'Punctuate writing accurately',
        'Avoid common punctuation errors',
        'Enhance writing clarity',
      ],
      topics: [
        'Comma rules and common mistakes',
        'Semicolons and colons',
        'Apostrophes for possession and contractions',
        'Quotation marks and dialogue',
        'Hyphens and dashes',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Proper punctuation is crucial for clear communication. Each punctuation mark serves a specific purpose, from separating clauses to indicating possession. Mastering punctuation prevents ambiguity and makes your writing professional.',
    },
    {
      id: 'english-day-4',
      day: 4,
      title: 'Writing Clear and Concise Sentences',
      description: 'Learn to write clear, effective sentences',
      objectives: [
        'Write clear, concise sentences',
        'Eliminate wordiness',
        'Improve sentence variety',
      ],
      outcomes: [
        'Craft effective sentences',
        'Identify and fix wordiness',
        'Use varied sentence structures',
      ],
      topics: [
        'Active vs passive voice',
        'Eliminating wordiness',
        'Sentence variety',
        'Avoiding run-on sentences',
        'Clarity and precision',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'Clear, concise writing is more effective than verbose prose. Active voice typically produces stronger sentences. Sentence variety keeps readers engaged. Learning to eliminate unnecessary words makes your writing more powerful and professional.',
    },
    {
      id: 'english-day-5',
      day: 5,
      title: 'Paragraph Structure and Flow',
      description: 'Master paragraph organization and transitions',
      objectives: [
        'Structure paragraphs effectively',
        'Use topic sentences',
        'Create smooth transitions',
      ],
      outcomes: [
        'Write well-organized paragraphs',
        'Guide readers through your writing',
        'Maintain logical flow',
      ],
      topics: [
        'Topic sentences',
        'Supporting details',
        'Concluding sentences',
        'Transition words and phrases',
        'Paragraph unity and coherence',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Paragraphs are the building blocks of effective writing. Each paragraph should focus on one main idea, introduced by a topic sentence and supported by relevant details. Smooth transitions between paragraphs guide readers through your thoughts.',
    },
    {
      id: 'english-day-6',
      day: 6,
      title: 'Professional Email Writing',
      description: 'Master business and professional email communication',
      objectives: [
        'Write professional emails',
        'Use appropriate tone and format',
        'Craft effective subject lines',
      ],
      outcomes: [
        'Communicate professionally via email',
        'Structure emails effectively',
        'Adapt tone to audience',
      ],
      topics: [
        'Email structure and format',
        'Subject lines that get opened',
        'Professional greetings and closings',
        'Tone and formality',
        'Email etiquette',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Email is a primary form of professional communication. Effective emails are clear, concise, and appropriately formal. The subject line, greeting, body, and closing all contribute to professionalism. Understanding email etiquette is essential in business environments.',
    },
    {
      id: 'english-day-7',
      day: 7,
      title: 'Technical Writing Basics',
      description: 'Learn to write clear technical documentation',
      objectives: [
        'Write clear technical content',
        'Organize technical information',
        'Use appropriate terminology',
      ],
      outcomes: [
        'Create understandable technical documents',
        'Structure technical information logically',
        'Write for technical audiences',
      ],
      topics: [
        'Technical writing principles',
        'Organizing technical information',
        'Writing procedures and instructions',
        'Using visuals effectively',
        'Audience analysis',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Technical writing communicates complex information clearly and concisely. It requires understanding your audience, organizing information logically, and using precise language. Good technical writing helps users understand and use technical products or concepts.',
    },
    {
      id: 'english-day-8',
      day: 8,
      title: 'Documentation and README Files',
      description: 'Master software documentation and README creation',
      objectives: [
        'Write effective README files',
        'Document code and projects',
        'Create user-friendly documentation',
      ],
      outcomes: [
        'Create professional README files',
        'Document projects effectively',
        'Help users understand your work',
      ],
      topics: [
        'README structure and content',
        'Installation instructions',
        'Usage examples',
        'API documentation',
        'Contributing guidelines',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'README files are often the first thing people see in your projects. Good documentation explains what your project does, how to use it, and how to contribute. Clear documentation is essential for collaborative development and project adoption.',
    },
    {
      id: 'english-day-9',
      day: 9,
      title: 'Code Comments and Inline Documentation',
      description: 'Learn to write effective code comments',
      objectives: [
        'Write helpful code comments',
        'Document code inline',
        'Balance comments with clean code',
      ],
      outcomes: [
        'Comment code effectively',
        'Make code self-documenting',
        'Help other developers',
      ],
      topics: [
        'When to comment code',
        'Writing helpful comments',
        'Docstrings and function documentation',
        'Avoiding obvious comments',
        'Comment best practices',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Good code comments explain why, not what. They help other developers (and future you) understand your reasoning. Balance is key: write self-documenting code when possible, but comment complex logic. Docstrings document function purposes and usage.',
    },
    {
      id: 'english-day-10',
      day: 10,
      title: 'Explaining Technical Concepts Simply',
      description: 'Master the art of simplifying complex topics',
      objectives: [
        'Explain technical concepts clearly',
        'Use analogies effectively',
        'Adapt explanations to audience',
      ],
      outcomes: [
        'Simplify complex ideas',
        'Communicate with non-technical audiences',
        'Use effective teaching techniques',
      ],
      topics: [
        'Avoiding jargon',
        'Using analogies and metaphors',
        'Breaking down complex concepts',
        'Visual aids and examples',
        'Audience awareness',
      ],
      duration: '2-3 hours',
      difficulty: 'Intermediate',
      content: 'Being able to explain technical concepts to non-technical audiences is a valuable skill. Use analogies, avoid jargon, and break concepts into digestible pieces. Good technical communication bridges the gap between experts and beginners.',
    },
    {
      id: 'english-day-11',
      day: 11,
      title: 'Writing for Different Audiences',
      description: 'Adapt your writing style to different readers',
      objectives: [
        'Identify audience needs',
        'Adjust tone and complexity',
        'Write for diverse readers',
      ],
      outcomes: [
        'Adapt writing to audience',
        'Choose appropriate style',
        'Communicate effectively across contexts',
      ],
      topics: [
        'Audience analysis',
        'Formal vs informal writing',
        'Technical vs general audiences',
        'Cultural considerations',
        'Accessibility in writing',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Different audiences require different approaches. Writing for executives differs from writing for developers or general users. Understanding your audience\'s knowledge level, needs, and preferences helps you communicate more effectively.',
    },
    {
      id: 'english-day-12',
      day: 12,
      title: 'Proofreading and Editing',
      description: 'Master the art of polishing your writing',
      objectives: [
        'Proofread effectively',
        'Edit for clarity and conciseness',
        'Catch common errors',
      ],
      outcomes: [
        'Produce error-free writing',
        'Improve writing quality',
        'Develop editing skills',
      ],
      topics: [
        'Proofreading techniques',
        'Common errors to watch for',
        'Editing for clarity',
        'Revising for conciseness',
        'Getting feedback',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Good writing is rewritten. Proofreading catches typos and grammar errors. Editing improves clarity, conciseness, and flow. Distance yourself from your writing before editing, and read it aloud to catch awkward phrasing.',
    },
    {
      id: 'english-day-13',
      day: 13,
      title: 'Common Grammar Mistakes',
      description: 'Identify and correct frequent grammar errors',
      objectives: [
        'Recognize common grammar mistakes',
        'Correct errors confidently',
        'Avoid future mistakes',
      ],
      outcomes: [
        'Identify grammar errors quickly',
        'Write with fewer mistakes',
        'Understand error causes',
      ],
      topics: [
        'Subject-verb agreement',
        'Pronoun usage',
        'Modifier placement',
        'Commonly confused words',
        'Sentence fragments',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Everyone makes grammar mistakes, but understanding common errors helps you avoid them. Subject-verb agreement, pronoun usage, and modifier placement trip up many writers. Learning to recognize and correct these errors improves your writing immediately.',
    },
    {
      id: 'english-day-14',
      day: 14,
      title: 'Professional Communication Skills',
      description: 'Master professional written communication',
      objectives: [
        'Communicate professionally',
        'Write business documents',
        'Develop professional tone',
      ],
      outcomes: [
        'Excel in professional communication',
        'Write various business documents',
        'Maintain appropriate professionalism',
      ],
      topics: [
        'Business letters and memos',
        'Reports and proposals',
        'Meeting minutes',
        'Professional tone',
        'Cross-cultural communication',
      ],
      duration: '2-3 hours',
      difficulty: 'Advanced',
      content: 'Professional communication requires clarity, courtesy, and appropriate formality. Different documents have different conventions. Understanding these conventions and adapting your style to professional contexts is essential for career success.',
    },
    {
      id: 'english-day-15',
      day: 15,
      title: 'Assessment Preparation and Practice',
      description: 'Prepare for English proficiency assessments',
      objectives: [
        'Apply cumulative English knowledge',
        'Practice assessment-style questions',
        'Build confidence',
      ],
      outcomes: [
        'Pass English proficiency assessments',
        'Demonstrate expert-level skills',
        'Communicate professionally',
      ],
      topics: [
        'Assessment format and expectations',
        'Practice exercises',
        'Common assessment topics',
        'Time management strategies',
        'Final review and tips',
      ],
      duration: '3-4 hours',
      difficulty: 'Advanced',
      content: 'This final module brings together all English concepts through assessment-style practice. You\'ll review key grammar rules, writing techniques, and professional communication skills. Comprehensive preparation ensures you\'re ready to demonstrate English proficiency.',
    },
  ],
};

export const outlierTipsCourse: Course = {
  id: 'outlier-tips',
  title: 'Outlier Assessment Playbook',
  description: 'Master the Outlier assessment format, scoring methodology, and proven strategies to pass on your first attempt.',
  icon: '🎯',
  color: 'from-purple-500 to-pink-500',
  totalDays: 1,
  difficulty: 'All Levels',
  modules: [
    {
      id: 'outlier-tips-1',
      day: 1,
      title: 'Understanding Outlier Assessments',
      description: 'Complete guide to Outlier assessment structure and scoring',
      objectives: [
        'Understand Outlier.ai assessment format',
        'Learn the scoring methodology',
        'Identify high-frequency test topics',
      ],
      outcomes: [
        'Explain the complete assessment structure',
        'Understand how Outlier scores your responses',
        'Know what assessors are looking for',
      ],
      topics: [
        'Assessment structure breakdown',
        'Scoring methodology (40% correctness, 25% quality, 15% efficiency, 10% completeness, 10% explanation)',
        'Multiple choice vs coding challenges vs code review',
        'Common mistakes that cause failures',
        '12 proven strategies to pass',
        'Time management techniques',
        'How to structure responses for maximum points',
      ],
      duration: '2-3 hours',
      difficulty: 'Beginner',
      content: 'This comprehensive guide reveals exactly how Outlier.ai assessments work, what they\'re looking for, and the proven strategies used by successful candidates. Learn the scoring rubric, common pitfalls, and insider tips from assessment experts.',
    },
    {
      id: 'outlier-tips-2',
      day: 1,
      title: '12 Proven Strategies to Pass',
      description: 'Expert strategies used by successful Outlier contractors',
      objectives: [
        'Learn 12 proven passing strategies',
        'Understand assessment day preparation',
        'Master response structuring techniques',
      ],
      outcomes: [
        'Apply strategies to improve assessment performance',
        'Prepare effectively for assessment day',
        'Structure responses for maximum scoring',
      ],
      topics: [
        'Strategy 1: Understand role requirements',
        'Strategy 2: Set up environment properly',
        'Strategy 3: Review fundamentals strategically',
        'Strategy 4: Practice under time pressure',
        'Strategy 5: Read instructions carefully',
        'Strategy 6: Plan before you code',
        'Strategy 7: Write clean, readable code',
        'Strategy 8: Handle edge cases',
        'Strategy 9: Use error handling appropriately',
        'Strategy 10: Test your code thoroughly',
        'Strategy 11: Manage your time effectively',
        'Strategy 12: Write helpful comments',
      ],
      duration: '1-2 hours',
      difficulty: 'Beginner',
      content: 'These 12 strategies are used by top-performing Outlier contractors to consistently pass assessments and unlock higher-paying projects. Each strategy includes detailed explanations, real examples, and practical implementation tips.',
    },
  ],
};

export const oneDayCourse: Course = {
  id: 'one-day-course',
  title: '2-Day Outlier Crash Course',
  description: 'Quick introduction to Git, Python, and English fundamentals. Get started with the essentials in just 2 days.',
  icon: '⚡',
  color: 'from-yellow-500 to-orange-500',
  totalDays: 2,
  difficulty: 'Beginner',
  modules: [
    {
      id: 'one-day-1',
      day: 1,
      title: 'Git & Python Fundamentals',
      description: 'Quick introduction to Git version control and Python basics',
      objectives: [
        'Understand Git basics and why it matters',
        'Write your first Python program',
        'Learn essential Git and Python commands',
      ],
      outcomes: [
        'Create and manage a Git repository',
        'Write simple Python programs',
        'Understand version control basics',
      ],
      topics: [
        'What is Git and why developers use it',
        'Basic Git commands: init, add, commit, push',
        'Introduction to Python',
        'Variables and data types',
        'Writing your first program',
      ],
      duration: '4-5 hours',
      difficulty: 'Beginner',
      content: 'This crash course covers the absolute essentials of Git and Python. You\'ll learn what Git is, why it\'s important, and how to use basic commands. You\'ll also write your first Python program and understand fundamental concepts like variables and data types.',
    },
    {
      id: 'one-day-2',
      day: 2,
      title: 'English Communication Essentials',
      description: 'Master essential English skills for professional communication',
      objectives: [
        'Understand English grammar fundamentals',
        'Write clear, professional sentences',
        'Communicate effectively in writing',
      ],
      outcomes: [
        'Write grammatically correct sentences',
        'Communicate professionally in writing',
        'Understand basic punctuation and capitalization',
      ],
      topics: [
        'Parts of speech and sentence structure',
        'Common grammar errors and corrections',
        'Punctuation and capitalization',
        'Writing clear, concise sentences',
        'Professional communication tips',
      ],
      duration: '4-5 hours',
      difficulty: 'Beginner',
      content: 'Learn the essentials of English grammar and professional communication. This module covers the most important grammar rules, common mistakes, and practical tips for writing clearly and professionally.',
    },
  ],
};

export const allCourses: Course[] = [outlierTipsCourse, oneDayCourse, gitCourse, pythonCourse, englishCourse];

export const getCourseById = (id: string): Course | undefined => {
  return allCourses.find(course => course.id === id);
};

export const getCourseTier = (courseId: string): 'lead-magnet' | 'upsell' | 'core' => {
  if (courseId === 'outlier-tips') return 'lead-magnet';
  if (courseId === 'one-day-course') return 'upsell';
  return 'core';
};

export const getModuleById = (courseId: string, moduleId: string): Module | undefined => {
  const course = getCourseById(courseId);
  return course?.modules.find(module => module.id === moduleId);
};

export const getFreeCourses = (): Course[] => {
  return [outlierTipsCourse, oneDayCourse];
};

export const getPaidCourses = (): Course[] => {
  return [gitCourse, pythonCourse, englishCourse];
};
